name: Publish NuGet Package

# Trigger the workflow when a tag starting with "v" is pushed
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup the required .NET SDK version
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      # Step 3: Calculate version using GitVersion
      - name: Setup GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.12

      # Step 4: Restore project dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Step 5: Build the project in Release configuration
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:Version=${{ steps.gitversion.outputs.fullsemver }}
      
      # Step 6: Pack
      - name: Pack NuGet Package
        run: dotnet pack --configuration Release --no-build /p:PackageVersion=${{ steps.gitversion.outputs.nugetversion }} --output ./nupkg

      # Step 7: Publish the package to NuGet using your API key
      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json